pool:
  name: Azure Pipelines  # Replace with the name of your agent pool
  demands:
    - Agent.OS -equals Linux  # Add specific demands if needed

jobs:
- job: Build
  displayName: Build
  pool:
    name: YourAgentPoolName  # Specify the agent pool for this job
  steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/path/to/Dockerfile'
        tags: |
          $(Build.SourceBranchName)-$(Build.BuildId)
